config/routes.rb
ContactBook::Application.routes.draw do
  resources :contacts

  root 'pages#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new contact_params
    if @contact.save
      redirect_to contacts_url
    else
      render 'new'
    end
  end
end



private

def contact_params
  params.require(:contact).permit(:name, :phone)
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/index.html.erb
<h1>Current Contacts</h1>

<ul>
  <% @contacts.each do |contact| %>
    <li><%= contact.name %> - <%= contact.phone %></li>
  <%end%>
</ul>

app/views/contacts/new.html.erb
<h1>Add a Contact</h1>
<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :phone %>
  <%= f.text_field :phone %><br>
  <%= f.label :email %>
  <%= f.text_field :email %><br>
  <%= f.label :company %>
  <%= f.text_field :company %><br>
  <%= f.submit %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactBook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <%= link_to "Contacts", contacts_path %>
  <%= link_to "Home", root_path %>
  <%= link_to "New Contact", new_contact_path %>
</nav>
<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>Home</h1>